name: PR Summarizer

permissions:
  pull-requests: write
  contents: read

on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install axios

      - name: Generate PR Summary
        id: summary
        run: |
          echo "Generating PR summary..."
          node generateSummary.js > summary.txt
          echo "::set-output name=summary::$(cat summary.txt)"

      - name: Debug PR Summary Output
        run: |
          echo "Summary generated: ${{ steps.summary.outputs.summary }}"
      
      - name: Post Summary as PR Comment
        run: |
          echo "Posting summary as PR comment..."
          gh pr comment ${{ github.event.pull_request.html_url }} --body "### PR Summary:\n\n${{ steps.summary.outputs.summary }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
