name: PR Summarizer
on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Ensures we can compare changes

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install axios

      - name: Generate PR Summary
        id: summary
        run: echo "::set-output name=summary::$(node generateSummary.js)"

      - name: Post Summary as PR Comment
        run: gh pr comment ${{ github.event.pull_request.html_url }} --body "### PR Summary:\n\n${{ steps.summary.outputs.summary }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
