name: Analyze PR for Affected ViewHolderFactory and Views

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Ensure all history is fetched

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Analyze PR for affected ViewHolderFactory and views
      id: analyze
      run: |
        echo "Analyzing PR for affected ViewHolderFactory and views..."
        CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
        echo "Changed files: $CHANGED_FILES"
        AFFECTED_FILES=""
        for FILE in $CHANGED_FILES; do
          if [[ $FILE == *"ViewHolderFactory"* || $FILE == *"view"* ]]; then
            echo "File affected: $FILE"
            AFFECTED_FILES+="$FILE\n"
          fi
        done
        echo "::set-output name=affected_files::$AFFECTED_FILES"
      shell: /usr/bin/bash -e {0}
      env:
        KOTLIN_HOME: /opt/hostedtoolcache/kotlin/2.0.21/x64/kotlinc

    - name: Comment on PR
      if: steps.analyze.outputs.affected_files != ''
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const viewtypesAffected = [
            "ViewHolderFactory: TYPE_0, TYPE_1, TYPE_2, TYPE_3",
            "MyAdapter: TYPE_0, TYPE_1, TYPE_2"
          ].join("\n");
          const affectedFiles = `\${{ steps.analyze.outputs.affected_files }}`;
          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: `The following files related to ViewHolderFactory and views have been affected:\n${affectedFiles}\n\nAffected viewtypes:\n${viewtypesAffected}`
          });
