name: PR Summary

on:
  pull_request:
    branches: [main] # Or your target branch
    types: [opened, synchronize, reopened] # Important: Add these triggers

jobs:
  summarize:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # Required to comment on PRs

    steps:
      - uses: actions/checkout@v3

      - name: Get PR Diff
        run: git diff --patch > diff.txt

      - name: Generate Summary (Gemini)
        id: gemini_summary
        uses: google-github-actions/generate-pull-request-summary@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          model: gemini
          prompt: |
            Summarize these code changes for a pull request. Focus on the key changes and the purpose of the PR.
            ```diff
            $(cat diff.txt)
            ```

      - name: Post Comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const summary = `${{ steps.gemini_summary.outputs.summary }}`;
            return github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## PR Summary (Gemini)\n${summary}`
            });
