name: PR RecyclerView Analysis
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  analyze_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch PR Diff
        run: gh pr diff ${{ github.event.pull_request.number }} > diff.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Analysis Script
        run: python analyze_pr.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Post Analysis Comment
        run: gh pr comment ${{ github.event.pull_request.number }} --body "$(cat analysis.txt)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
