name: PR Analysis with Gemini AI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  analyze_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          pip install google
          
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get PR Diff
        run: |
          PR_DIFF=$(gh pr diff ${{ github.event.pull_request.number }} --repo ${{ github.repository }})
          echo "$PR_DIFF" > pr_diff.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Analyze PR using Gemini AI
        run: |
          python analyze_pr.py > pr_analysis_output.yaml

      - name: Comment on PR with AI Analysis
        run: |
          COMMENT_BODY=$(cat pr_analysis_output.yaml)
          gh pr comment ${{ github.event.pull_request.number }} --body "### PR Analysis (AI-generated)\n\`\`\`yaml\n$COMMENT_BODY\n\`\`\`"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
