name: Pull Request Summary

on:
  pull_request:
    types: [opened, edited]

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Summary
        run: |
          echo "Summary of changes in the PR:"
          git log --oneline -n 5
