name: Copilot Integration

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  analyze-changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install OpenAI
      run: pip install openai

    - name: Get PR Diff
      run: |
        git diff origin/main...HEAD > diff.txt

    - name: Analyze View and ViewHolder Changes
      run: |
        python analyze_pr.py

    - name: Comment on PR with changes
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        header: View and ViewHolder Changes
        message: |
          The following analysis was performed on the PR changes:
          ```
          $(cat analysis.txt)
          ```
