name: Code Review

on:
  pull_request:
    branches: [main]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Gemini Code Reviewer
        id: gemini_review  # Give the step an ID
        uses: truongnh1992/gemini-ai-code-reviewer@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          prompt: |
            Summarize this pull request, focusing on changes related to RecyclerView adapters.
            Specifically, identify any modifications to getItemViewType methods and associated ViewHolders.
            If possible, list the affected classes and methods.

      - name: Debug Output (Print to console)
        run: |
          echo "Gemini Output:"
          echo "${{ steps.gemini_review.outputs.review_summary }}"  # Access output

      - name: Post Comment (Only if review_summary exists)
        if: steps.gemini_review.outputs.review_summary != ''  # Check if empty
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const review_summary = `${{ steps.gemini_review.outputs.review_summary }}`;
            return github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## Code Review Summary\n${review_summary}`
            });
