name: Code Review

on:
  pull_request:
    branches: [main] # or your main branch name

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: truongnh1992/gemini-ai-code-reviewer@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Important!
          # Optional: You can customize the prompt if needed
          prompt: |
            Summarize this pull request, focusing on changes related to RecyclerView adapters.
            Specifically, identify any modifications to getItemViewType methods and associated ViewHolders.
            If possible, list the affected classes and methods.

          # Optional: You can specify a list of files/directories to include or exclude
          # include: 'src/**/*.java'
          # exclude: '**/test/**'
