name: Analyze PR for Affected ViewHolderFactory and Views

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  analyze_pr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Setup Kotlin
      uses: fwilhe2/setup-kotlin@v1

    - name: Analyze PR
      run: |
        echo "Analyzing PR for affected ViewHolderFactory and views..."
        CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }})
        
        echo "Changed files: $CHANGED_FILES"

        for FILE in $CHANGED_FILES; do
          if [[ $FILE == *"ViewHolderFactory"* || $FILE == *"view"* ]]; then
            echo "File affected: $FILE"
          fi
        done
