name: Gemini AI Code Reviewer

on:
  issue_comment:
    types: [created]

permissions: write-all

jobs:
  gemini-code-review:
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/gemini-review')
    steps:
      - name: PR Info
        run: |
          echo "Comment: ${{ github.event.comment.body }}"
          echo "Issue Number: ${{ github.event.issue.number }}"
          echo "Repository: ${{ github.repository }}"

      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get PR Details
        id: pr
        run: |
          PR_JSON=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.issue.number }})
          echo "head_sha=$(echo $PR_JSON | jq -r .head.sha)" >> $GITHUB_OUTPUT
          echo "base_sha=$(echo $PR_JSON | jq -r .base.sha)" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch Base and Head Branches
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1
          git fetch origin ${{ github.head_ref }} --depth=1
          git checkout -b base_branch origin/${{ github.base_ref }}
          git checkout ${{ github.head_ref }}

      - name: Identify ViewHolder classes and view types
        run: |
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }}..${{ github.head_ref }})
          echo "Changed files: $CHANGED_FILES"
          echo "Input to script:"
          echo "$CHANGED_FILES"
          VIEWHOLDER_CLASSES=$(git diff origin/${{ github.base_ref }}..${{ github.head_ref }} -- '*.java' '*.kt' | grep -E 'class .*ViewHolder' | awk '{print $2}')
          echo "ViewHolder Classes: $VIEWHOLDER_CLASSES"
          echo "Input to script:"
          echo "$VIEWHOLDER_CLASSES"
          VIEW_TYPES=$(git diff origin/${{ github.base_ref }}..${{ github.head_ref }} -- '*.java' '*.kt' | grep -E 'itemView\.' | awk -F '.' '{print $2}' | sort | uniq)
          echo "View Types: $VIEW_TYPES"
          echo "Input to script:"
          echo "$VIEW_TYPES"
          if [[ -n "$VIEWHOLDER_CLASSES" || -n "$VIEW_TYPES" ]]; then
            echo "::set-output name=view_changes::true"
            echo "::set-output name=viewholder_classes::$VIEWHOLDER_CLASSES"
            echo "::set-output name=view_types::$VIEW_TYPES"
          else
            echo "No ViewHolder-related changes detected."
            echo "::set-output name=view_changes::false"
          fi

      - uses: truongnh1992/gemini-ai-code-reviewer@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GEMINI_MODEL: gemini-1.5-pro-002 # Optional, default is `gemini-1.5-flash-002`
          INPUT_EXCLUDE: "*.md,*.txt,package-lock.json,*.yml,*.yaml"

      - name: Summarize PR using Gemini model
        if: steps.check-view-changes.outputs.view_changes == 'true'
        run: |
          SUMMARY=$(curl -X POST "https://api.gemini.com/summarize" \
            -H "Authorization: Bearer ${{ secrets.GEMINI_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d "{\"text\": \"ViewHolder Classes: ${{ steps.check-view-changes.outputs.viewholder_classes }}\nView Types: ${{ steps.check-view-changes.outputs.view_types }}\"}")
          echo "PR Summary: $SUMMARY"
